INSERT INTO public.shopify_projects
 (slug, name, platform, industry, short_description, challenge, audit_findings, solution, results, business_impact, desktop_image, mobile_image, hero_image, featured, published, sort_order, meta_title, meta_description)
VALUES
('dopple-press','Dopple Press','Wix','Art & Print Studio',
 'A Wix riso-print studio and shop, restructured so limited artist collaborations lead the homepage and shoppers reach a print in fewer clicks.',
 'Dopple Press had a striking, art-led Wix site, but the shop was buried behind editorial imagery. Visitors admired the artwork and left without ever reaching a product page, and the limited artist drops that drive most sales were not visible above the fold.',
 'The audit showed the homepage loaded several full-bleed images before any shopping entry point, mobile navigation hid Cart and Print behind an unlabelled control, product tiles gave no price or availability signal, and heavy uncompressed imagery slowed first paint on mobile.',
 'I restructured the homepage around the limited artist collaborations band, pulled Cart, Print and Blog into a persistent, clearly labelled navigation, added price and availability to every collaboration tile, and compressed and lazy-loaded the gallery imagery so the first screen renders fast on phones.',
 'Product pages became reachable in one tap from the homepage, mobile load time dropped noticeably, and the artist drops now sit at the top of the page where visitors actually see them.',
 'More of the studio''s existing traffic now reaches a purchasable print instead of bouncing from the gallery, and each new artist collaboration gets a clear, repeatable launch slot on the homepage.',
 '/__l5e/assets-v1/78fd6ed0-8d2e-44e1-8c6a-3a8ef1d3e3b8/Macbook-Air-www.dopplepress.com.png',
 '/__l5e/assets-v1/b6992be5-b13b-4149-8543-d7ba7feab4b0/iPhone-14-PRO-www.dopplepress.com.png',
 '/__l5e/assets-v1/78fd6ed0-8d2e-44e1-8c6a-3a8ef1d3e3b8/Macbook-Air-www.dopplepress.com.png',
 true,true,10,'Dopple Press — Wix Art Shop Conversion Case Study','How I restructured the Dopple Press Wix shop so limited artist collaborations lead the page and prints are one tap away.'),
('package-free-shop','Package Free Shop','Wix','Eco Home & Cleaning',
 'A plastic-free home cleaning brand, with the hero, product storytelling and mobile buying path rebuilt around one clear promise per screen.',
 'Package Free Shop sells a considered, values-led product, but the homepage asked visitors to absorb the sustainability story and the product range at the same time. Mobile shoppers scrolled a long way before meeting a single reason to buy.',
 'The audit found a hero with two competing calls to action and no visible primary, product benefit claims (300 loads, ultra concentrated, hypoallergenic) buried inside pack imagery rather than in text, no announcement-bar urgency for the upcoming pods launch, and a mobile hero image that pushed the buttons off the first screen.',
 'I gave the hero one dominant call to action with the secondary demoted to a text link, lifted the key product claims out of the packaging into scannable benefit text, reworked the mobile hero so headline, subline and buttons all sit above the fold, and used the announcement bar for a single timed message tied to the plastic-free pods launch.',
 'The first screen now states the promise, the proof and the next step on both desktop and mobile, and the coming-soon launch has a permanent, measurable entry point.',
 'Visitors reach the best-selling collection sooner and with more reason to buy, and the brand story now supports the sale instead of competing with it.',
 '/__l5e/assets-v1/8cf68e98-cff4-418f-897e-cf55222343e2/Macbook-Air-packagefreeshop.com.png',
 '/__l5e/assets-v1/8605f6e9-80c6-4426-add4-c9b4e39d0a7d/iPhone-14-PRO-packagefreeshop.com.png',
 '/__l5e/assets-v1/8cf68e98-cff4-418f-897e-cf55222343e2/Macbook-Air-packagefreeshop.com.png',
 true,true,20,'Package Free Shop — Wix Homepage & Mobile CRO Case Study','How I rebuilt the Package Free Shop hero and mobile buying path around one clear promise and one primary call to action.'),
('izzy-wheels','Izzy Wheels','Wix','Accessible Design & Ecommerce',
 'An award-winning designer wheelchair wheel cover brand, with the Wix storefront tightened so the licensed collections and shop path carry the homepage.',
 'Izzy Wheels has an unusually strong brand and licensed Disney and Marvel collections, but the homepage spent its most valuable space on a large hero video before offering any way to shop. The single Shop Designs button sat far below the fold on mobile.',
 'The audit flagged a hero that filled the whole first screen with no visible call to action, a top navigation of eight items competing for attention, product thumbnails with no names or prices, and a currency selector taking prime mobile header space ahead of the menu and the shop link.',
 'I brought Shop Designs into the hero itself, tightened the navigation to the paths that convert, added names, prices and licence badges to the featured wheel covers, and reordered the mobile header so the menu and shop link lead and the currency selector steps back.',
 'The homepage now moves visitors from the brand statement straight into the collection, and the licensed ranges are recognisable at a glance rather than after a click.',
 'The brand''s considerable press and social traffic lands on a page that sells, and the Disney and Marvel collaborations get the shelf space they deserve.',
 '/__l5e/assets-v1/7c1312ac-7127-4154-a6b9-376df9ff9678/Macbook-Air-www.izzywheels.com.png',
 '/__l5e/assets-v1/5eacb05e-1dc0-41f2-9bac-6b069cbc95c4/iPhone-14-PRO-www.izzywheels.com.png',
 '/__l5e/assets-v1/7c1312ac-7127-4154-a6b9-376df9ff9678/Macbook-Air-www.izzywheels.com.png',
 true,true,30,'Izzy Wheels — Wix Storefront Conversion Case Study','How I tightened the Izzy Wheels Wix homepage so the licensed wheel cover collections and the shop path lead the page.');